#include <stdio.h>

int main(void)
{
  int INPUT_SECONDS, REMAINING_SECONDS, HOURS, MINUTES, SECONDS;
  int SECONDS_IN_MINUTE = 60;
  int SECONDS_IN_HOUR = (SECONDS_IN_MINUTE * 60); 

  printf("Gimme seconds:");
  scanf("%d", &INPUT_SECONDS);
  
  HOURS = (INPUT_SECONDS/SECONDS_IN_HOUR);
  
  REMAINING_SECONDS = INPUT_SECONDS - (HOURS * SECONDS_IN_HOUR);

  MINUTES = REMAINING_SECONDS/SECONDS_IN_MINUTE;

  REMAINING_SECONDS = REMAINING_SECONDS - (MINUTES*SECONDS_IN_MINUTE);
  
  SECONDS = REMAINING_SECONDS;
  
  printf("%d hour, %d minutes and %d seconds",HOURS, MINUTES, SECONDS);
}
